package:
  name: happler
  version: v0.0.0

source:
  path: '..'

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"
  entry_points:
    - happler = happler.__main__:main
  noarch: python

requirements:
  host:
    - pip >=19.0.3
    - python >=3.7
    - poetry-core >=1.0.0
  run:
    - python >=3.7
    - statsmodels >=0.13.2
    - click >=8.0.4
    - networkx >=2.6.3
    - scipy >=1.7.3
    - pydot >=1.4.2

about:
  home: https://github.com/gymrek-lab/happler
  license: MIT
  summary: 'A haplotype-based fine-mapping method'
  dev_url: https://github.com/gymrek-lab/happler
  doc_url: https://happler.readthedocs.io/
  doc_source_url: https://github.com/shibukawa/imagesize_py/blob/master/README.rst
