channels:
  - conda-forge
  - nodefaults
dependencies:
  - poetry==1.1.15
  - python=3.7
  - statsmodels==0.13.2 # this belongs in pyproject.toml but we've pinned it here for now b/c of https://github.com/statsmodels/statsmodels/issues/8200
  - gxx_linux-64

