[tool.poetry]
name = "happler"
version = "0.0.1"
description = "A haplotype-based fine-mapping method"
authors = ["Arya Massarat"]
license = "MIT"
repository = "https://github.com/aryarm/happler"
homepage = "https://github.com/aryarm/happler"

[tool.poetry.dependencies]
python = "^3.7"
click = "^8.0.3"
pysam = "^0.17.0"
cyvcf2 = "^0.30.12"
networkx = "^2.6.3"

[tool.poetry.dev-dependencies]
pytest = "^6.2.5"
black = "^21.10b0"
sphinx = {version = "^4.2.0", optional = true}
sphinx-autodoc-typehints = "^1.12.0"
sphinx-rtd-theme = "^1.0.0"
ipython = "^7.29.0"
numpydoc = "^1.1.0"

[tool.poetry.extras]
docs = ["sphinx", "sphinx-autodoc-typehints", "sphinx-rtd-theme", "numpydoc"]

[tool.poetry.scripts]
happler = 'happler.__main__:main'

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
