channels:
    - conda-forge
    - bioconda
    - nodefaults
dependencies:
    - bioconda::bcftools==1.13
    - conda-forge::datamash==1.7
    - conda-forge::pandas==1.3.0
    - conda-forge::seaborn==0.11.1
    - conda-forge::coreutils==8.31
    - conda-forge::sed==4.8
    - conda-forge::bash==5.0.018
    - conda-forge::gzip==1.10
    - conda-forge::click==8.1.7
    - bioconda::plink2==2.00a5.10
    - conda-forge::graphviz==2.50.0
    - conda-forge::scikit-learn==1.5.1
    - bioconda::igv==2.17.4
    - conda-forge::ipython # for debugging
