# This is the Snakemake configuration file that specifies paths and 
# and options for the pipeline. Anybody wishing to use
# the provided snakemake pipeline should first fill out this file with paths to
# their own data, as the Snakefile requires it.
# Every config option has reasonable defaults unless it is labeled as "required."
# All paths are relative to the directory that Snakemake is executed in.
# Note: this file is written in the YAML syntax (https://learnxinyminutes.com/docs/yaml/)


# Paths to a SNP-STR haplotype reference panel for 1000G
# You can download this from http://gymreklab.com/2018/03/05/snpstr_imputation.html
# If the VCFs are per-chromosome, replace the contig name in the file name with "{chr}"
# The VCF(s) must be sorted and indexed (with a .tbi file in the same directory)
# The variant IDs of STRs must have 'STR_' prepended
# required!
# ref_panel: "/projects/ps-gymreklab/resources/datasets/snpstr/1kg.snp.str.chr{chr}.vcf.gz"
snp_panel: "/projects/ps-gymreklab/resources/datasets/ukbiobank/array_imputed/pfile_converted/chr{chr}.pgen"
str_panel: "/projects/ps-gymreklab/jmargoli/ukbiobank/str_imputed/runs/first_pass/vcfs/annotated_strs/chr{chr}.vcf.gz"

# Path to a list of samples to exclude from the analysis
# There should be one sample ID per line
exclude_samples: data/ukb_withdrawals.tsv

# If variants are unphased, provide the path to a SHAPEIT4 map file like these:
# https://github.com/odelaneau/shapeit4/tree/master/maps
phase_map: data/genetic_maps/chr{chr}.b37.gmap.gz

# A list of loci, specifying variants to use within the simulations
# Each locus can be specified as a dict composed of two keys:
# 1. "locus" - a string with a contig name, a colon, the start position, a dash, and the
# end position
# 2. "str" - a string with a contig name, a colon, and the start position
# 3. (optionally) "snp" - same format as "str"
#   If this key is not provided, a random SNP will be chosen.
# The STR and SNP positions should be contained within the locus.
# The positions should be provided in the same coordinate system as the reference
# genome of the VCF files.
# The contig should correspond with the contig name from the {chr} wildcard in the VCF
# required!
loci:
 # - locus: 1:98001984-99001984
 #   str: 1:98506615
 #   snp: 1:98501984
 - locus: 19:45401409-46401409 # center: 45901409 (APOe4)
   # str: 19:45903857 # STR_691361
   snp: 19:45910672 # rs1046282
   hap: [rs36046716:G, rs1046282:G] # 45892145, 45910672
#  - locus: 10:104457618-105457618
#    str: 10:104639652
#    snp: 10:104612335
   # - locus: 16:56927279-57084844

# Discard rare variants with a MAF below this number
# Defaults to 0 if not specified
min_maf: 0.1

# The strength of association between the chosen STR or SNP and the simulated phenotype
# Defaults to 0.1 if not specified
# You can also provide a list of floats, if you want to test several beta values
beta: [0.05]

# Whether to include the causal variant in the set of genotypes provided to the
# finemapping methods. Set this to true if you're interested in seeing how the
# methods perform when the causal variant is absent from the data.
# Defaults to false if not specified
# You can also provide a list of booleans, if you want to test both values
exclude_causal: [true, false]
